#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/c9e30dbb-b509-4fa2-8b9d-7c48375f7a5c 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float debit;
  float waterLevel;
  CloudLight pumpState;
  int debitDesire;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
static bool pump = false ; 
#define SENSOR_PIN 34
#define PUMP1 12
#define PUMP2 13 
#define SAMPLING_TIME 10
float prevLevel = 0 ; 


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  pinMode(2,OUTPUT);
  pinMode(SENSOR_PIN , INPUT);
  pinMode(PUMP1,OUTPUT);
  pinMode(PUMP2,OUTPUT);
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  waterLevel = analogRead(SENSOR_PIN);
  debit = (waterLevel - prevLevel)/(SAMPLING_TIME / 1000.0);
  prevLevel = waterLevel ;  
  delay(SAMPLING_TIME);
  
}



/*
  Since WaterLevel is READ_WRITE variable, onWaterLevelChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onWaterLevelChange()  {
  // Add your code here to act upon WaterLevel change
}

/*
  Since Debit is READ_WRITE variable, onDebitChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDebitChange()  {
  // Add your code here to act upon Debit change
}



/*
  Since PumpState is READ_WRITE variable, onPumpStateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPumpStateChange()  {
  // Add your code here to act upon PumpState change
  if(pump == false) { 
  digitalWrite(2,1);
  analogWrite(PUMP1,debitDesire);
  analogWrite(PUMP2,0);
  pump = true ; 
  }
  else {
  digitalWrite(2,0);
  analogWrite(PUMP2,0);
  analogWrite(PUMP1,0);
  pump = false ; 
  }
}




/*
  Since DebitDesire is READ_WRITE variable, onDebitDesireChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDebitDesireChange()  {
analogWrite(PUMP1,debitDesire);
analogWrite(PUMP2,0);
}