// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "500482b8-6f72-49f9-9582-556e50743c7f";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDebitChange();
void onWaterLevelChange();
void onPumpStateChange();
void onDebitDesireChange();

float debit;
float waterLevel;
CloudLight pumpState;
int debitDesire;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(debit, READWRITE, ON_CHANGE, onDebitChange);
  ArduinoCloud.addProperty(waterLevel, READWRITE, ON_CHANGE, onWaterLevelChange);
  ArduinoCloud.addProperty(pumpState, READWRITE, ON_CHANGE, onPumpStateChange);
  ArduinoCloud.addProperty(debitDesire, READWRITE, ON_CHANGE, onDebitDesireChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
